#!/bin/bash -ex

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

WEBROOT=/var/www/appflower
git clone https://github.com/appflower/appflower_studio_playground.git $WEBROOT
cd $WEBROOT
git submodule init
git submodule update

unset HTTP_PROXY

