#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="1.3"
URL="http://cdn.appflower.com/appflower_studio_playground_vendors-${VERSION}.tgz"

dl $URL /usr/local/src

