#!/bin/bash -ex

URL="https://github.com/appflower/appflower_studio_playground/archive/v1.3.0.tar.gz"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY "$URL" -o /usr/local/src/appflower.tar.gz

