#!/bin/bash -ex

DB_NAME=appflower
DB_USER=appflower
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/appflower

# unpack
tar -zxf $SRC/appflower_studio_playground_vendors-*.tgz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/appflower_studio_playground $WEBROOT
rm $SRC/appflower_studio_playground_vendors-*.tgz
chown -R root:root $WEBROOT

# php tweaks
PHPINI1=/etc/php5/apache2/php.ini
PHPINI2=/etc/php5/cli/php.ini

sed -i "s|^short_open_tag = On|short_open_tag = Off|" $PHPINI1
sed -i "s|^short_open_tag = On|short_open_tag = Off|" $PHPINI2

# verify configuration
php5 $WEBROOT/lib/vendor/symfony/data/bin/check_configuration.php

# configure apache
a2dissite default
a2ensite appflower
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

CONF=$WEBROOT/config/databases.yml
sed -i "s|dsn:.*|dsn:        mysql:dbname=$DB_NAME;host=localhost|" $CONF
sed -i "s|username:.*|username:   $DB_USER|" $CONF
sed -i "s|password:.*|password:   $DB_PASS|" $CONF

CONF=$WEBROOT/config/propel.ini
sed -i "s|mysql:dbname=.*|mysql:dbname=$DB_NAME;host=localhost|" $CONF
sed -i "s|database.user.*|database.user       = $DB_USER|" $CONF
sed -i "s|database.password.*|database.password   = $DB_PASS|" $CONF

sed -i "s|appflower_playground|appflower|g" $CONF
sed -i "s|/www/.*|$WEBROOT|" $CONF

# set project permissions
$WEBROOT/symfony project:permission
$WEBROOT/symfony afs:fix-perms

# build database
$WEBROOT/symfony propel:build-model
echo -e "y\\n" | $WEBROOT/symfony propel:insert-sql

# build cache
$WEBROOT/symfony appflower:validator-cache frontend cache yes

# set default password
SHA1_PASS=$(echo -n $ADMIN_PASS | sha1sum | cut -d " " -f 1)
CONF=$WEBROOT/plugins/appFlowerStudioPlugin/config/users.yml
sed -i "s|password:.*|password: $SHA1_PASS|g" $CONF

# stop services
/etc/init.d/mysql stop

