#!/bin/bash -ex

DB_NAME=appflower
DB_USER=appflower
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/appflower

# unpack
tar -zxf $SRC/appflower_studio_playground_vendors-*.tgz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/appflower_studio_playground $WEBROOT
rm $SRC/appflower_studio_playground_vendors-*.tgz
chown -R root:root $WEBROOT

