#!/bin/bash -e
# regenerate appflower secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/appflower/apps/frontend/config/filters.yml
sed -i "s|secret:.*|secret: $(mcookie)|" $CONF

PASSWORD=$(mcookie)
CONF=/var/www/appflower/config/databases.yml
sed -i "s|password:.*|password:   $PASSWORD|" $CONF

CONF=/var/www/appflower/config/propel.ini
sed -i "s|database.password.*|database.password   = $PASSWORD|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=appflower --pass="$PASSWORD"

